[LAB-3] Local storage
easuck/effective-marvel-app pull request #3
Opened 2024-04-04 12:48 UTC by easuck

2024-04-09 16:41 UTC, konstantinzelinsky requested changes
Не очень оптимальное решение с избранным.
Если бы я в следующей работе потребовал добавить какие-то еще данные в localStorage, то данную работу и логику с избранным пришлось бы переделывать
7 + 2

2024-04-09 16:41 UTC, konstantinzelinsky commented on src/pages/favourites/Favourites.tsx
> +                {Object.keys(localStorage).map((key) => {
Если в localStorage будут лежать какие-то еще данные, то эта логика не будет работать. Нужно хранить все данные в localStorage под одним ключом - favourites. Это должен быть массив.
Так же на данный момент логика удаления элемента из избранного работает только по той причине, что этот компонент перерендеривается из-за изменения favouritesAmount. Если бы в этом компоненте не было данной переменной, то список бы не изменился, так как Реакт не реагирует на изменения localStorage.

2024-04-09 16:41 UTC, konstantinzelinsky commented on src/hooks/useLocalStorage.ts
> +const useLocalStorage = (setFavouritesAmount: (amount: number) => void, favouritesAmount: number) => {
хук должен представлять из себя какой-то взаимодействие с React API. Использовать какие-то другие хуки например (useState, useEffect...) внутри себя
В данном случае это не хук, а набор функций-хелперов, которые стоит поместить в папку helpers

2024-04-09 16:41 UTC, konstantinzelinsky commented on src/components/card/Card.tsx
> +        if (getItem(id.toString())) setIsFavourite(true)
Каждая карточка это отдельный запрос к localStorage из-за того, что все элементы в нем хранятся с разными ключами. Их нужно хранить как массив, чтобы получать этот массив за одно обращение.
К localStorage должно быть только 2 обращения по сути - получить массив, обновить массив (добавить/удалить элемент)
Вся остальная работа с стейтом Реакта или с стором. То есть используя стейт, проверяем является ли элемент избранным или нет

2024-04-11 05:44 UTC, konstantinzelinsky approved these changes
Остался небольшой момент
Балл повысил до 9 + 2

2024-04-11 05:44 UTC, konstantinzelinsky commented on src/components/card/Card.tsx
> +                         const newFavourites: LocalStorageEntity[] = getItem("favourites").filter(item => item.id != id);
Здесь нет необходимости обращаться к localStorage. У тебя есть переменная favourites, которая содержить такие же данные
const newFavourites = favourites.filter(item => item.id != id)

2024-04-11 05:44 UTC, konstantinzelinsky commented on src/components/card/Card.tsx
> +                         let newFavourites: LocalStorageEntity[] = JSON.parse(localStorage.getItem("favourites"));
Здесь нет необходимости обращаться к localStorage. У тебя есть переменная favourites, которая содержить такие же данные
const newFavourites = [...favourites, newFavourite]

2024-04-11 18:06 UTC, easuck commented on src/components/card/Card.tsx
> +                         let newFavourites: LocalStorageEntity[] = JSON.parse(localStorage.getItem("favourites"));
Хорошо, я поправил

2024-04-11 18:06 UTC, merged